<?php

namespace app\modules\cp\controllers;

use app\components\helpers\BreadcrumbsHelper;
use yii\web\Controller;
use Yii;


class CpController  extends Controller {

    public $layout='@app/modules/common/views/layouts/main';

    public function beforeAction($action)
    {
        BreadcrumbsHelper::add(Yii::t('app','Dashboard'), '/cp', 'bars');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions()
    {

        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


}